### ISSUE TITLE
ES6 support?

### ISSUE THREAD

**Issue by kshmir** [dsfields/couchbase-promises#1]
I was wondering if this library can work with ES6 directly, without using a polyfill.

Cheers!

**Comment by dsfields** [comment]
I had given some thought to adding support for ES6 promises as a configurable option.  I'm not entirely sure what the point would be.  Bluebird promises are still considerably faster than the ES6 implementation.  Additionally, since Bluebird follows the A+ spec, the two should be compatible with one another.

I'm definitely open to the idea.  What's your reasoning?

**Comment by kshmir** [comment]
I understand your reasoning, but I prefer to be able to avoid polyfills when the language can solve it by itself in the latest versions (node v4/v5).
It is also something that can be solved with transpiling and not a library, or at least, it should be configurable, right now it is a fixed dependency.

**Comment by dsfields** [comment]
I understand, and I generally agree with you.  Promises are an exception.  Promises in V8 are notoriously slow memory hogs.  Bluebird solves that issue.  I'll present two options.  Pick one:

a.) I add a configurable property that allows you to specify the use of ES6 promises.
b.) I fork the library, and publish a new module called couchbase-es-promises (or something like that).

I'm a bigger fan of option "b," as option "a" will still leave the module dependency in place.  Plus, option b is much cleaner and easier to implement.

**Comment by kshmir** [comment]
Option b looks like the best for me!

On Sunday, December 6, 2015, Dan Fields notifications@github.com wrote:

> I understand, and I generally agree with you. Promises are an exception.
> Promises in V8 are notoriously slow memory hogs. Bluebird solves that
> issue. I'll present two options. Pick one:
> 
> a.) I add a configurable property that allows you to specify the use of
> ES6 promises.
> b.) I fork the library, and publish a new module called
> couchbase-es-promises (or something like that).
> 
> I'm a bigger fan of option "b," as option "a" will still leave the module
> dependency in place. Plus, option b is much cleaner and easier to implement.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dsfields/couchbase-promises/issues/1#issuecomment-162359578
> .

## 

Cristian Pereyra

**Comment by dsfields** [comment]
I'm on it.

**Comment by dsfields** [comment]
This is done: https://www.npmjs.com/package/couchbase-es-promises
