### ISSUE TITLE
on SUSE linux 11 SP4, npm install couchbase-promises failed

### ISSUE THREAD

**Issue by robertchen** [dsfields/couchbase-promises#19]
ip-10-8-8-110:~/# npm install couchbase-promises
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global node-gyp@3.5.0 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g

> couchbase@2.3.0 install /root/nodejs-test/node_modules/couchbase
> prebuild --install

sh: prebuild: command not found
npm ERR! Linux 3.0.101-94-ec2
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "couchbase-promises"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! couchbase@2.3.0 install: `prebuild --install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the couchbase@2.3.0 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the couchbase package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs couchbase
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls couchbase
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/nodejs-test/npm-debug.log

**Comment by dsfields** [comment]
Hello Robert,

This is actually an issue with the underlying native `couchbase` module.  I'll do some digging to see if I can find a proper fix.  In the meantime, installing the `prebuild` module ahead of time should offer an interim workaround.

**Comment by dsfields** [comment]
This is something that really needs to get fixed by the Couchbase folks.  I'm going to close this one out.
